'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AgentProfile
    
    '''<summary>
    '''pnl_showgridview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_showgridview As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddl_criteria control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_criteria As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txt_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_search As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_clear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_clear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ddlPaging control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPaging As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''chkStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStatus As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''rptPager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPager As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''btn_bulksend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_bulksend As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_export control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_export As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnl_showDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_showDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txt_Code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Code As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_AddType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AddType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_Lname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Lname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_add1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_add1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_Fname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Fname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_add2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_add2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_gender control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_gender As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_add3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_add3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_dob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_dob As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_add4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_add4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_id As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_add5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_add5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_salution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_salution As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_PosCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_PosCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_nationality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nationality As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_email control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_email As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_CountryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CountryCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_Mphone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Mphone As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_marryStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_marryStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_hp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hp1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_pass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_pass As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_hp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hp2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_TaxStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_TaxStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_LicenseNumC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LicenseNumC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_NPWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NPWP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_LicenseExpiryC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LicenseExpiryC As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_Religion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Religion As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_LicenseNumS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LicenseNumS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_HireDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_HireDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_LicenseExpiryS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LicenseExpiryS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_terminateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_terminateDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_bankcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bankcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_AgentType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AgentType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_AccNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AccNum As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_AgentStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AgentStatus As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_AccHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_AccHolder As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_channel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_channel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_UpdateDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_UpdateDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_LeaderCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LeaderCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txt_LastLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_LastLogin As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlDevStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDevStatus As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btn_resend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_resend As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_resetPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_resetPass As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_back control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_back As Global.System.Web.UI.WebControls.Button
End Class
