'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Site
    
    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead
    
    '''<summary>
    '''HeadContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HeadContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
    
    '''<summary>
    '''Form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Form1 As Global.System.Web.UI.HtmlControls.HtmlForm
    
    '''<summary>
    '''btn_lgout control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_lgout As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''sidebar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sidebar As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Agent_Profile control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Agent_Profile As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Table_Maintenance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Table_Maintenance As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TMCONNECT_Version control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TMCONNECT_Version As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''User_Management control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents User_Management As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Edit_TMCONNECT_Client control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_TMCONNECT_Client As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Edit_TMCONNECT_Server control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Edit_TMCONNECT_Server As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SPAJ_Admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPAJ_Admin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''VA_Number_Listing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VA_Number_Listing As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''SPAJ_Submission_List control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SPAJ_Submission_List As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''STP_Rules_Table control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STP_Rules_Table As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Product_Configurator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Product_Configurator As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''TMCONNECT_Client_Photos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TMCONNECT_Client_Photos As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''Payment_Lsting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Payment_Lsting As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''MainContent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainContent As Global.System.Web.UI.WebControls.ContentPlaceHolder
End Class
